version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/tradingbot-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      fastapi-stack:
        patterns:
          - "fastapi"
          - "starlette"
          - "anyio"
          - "httpx"
          - "httpcore"
          - "h11"
  - package-ecosystem: "npm"
    directory: "/frontend/dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      vite-react:
        patterns:
          - "vite*"
          - "react*"
          - "@types/react*"
    allow:
      - dependency-type: "direct"
