"""
Models Package - TradingBot Backend

Detta paket innehåller alla datamodeller som används i tradingboten.
"""

from models.api_models import (  # Enums; Wallet-modeller; Margin-modeller; Position-modeller; Order-modeller; Marknadsdata-modeller; Websocket-modeller; API-svar-modeller
    ApiResponse,
    Candle,
    ClosePositionResponse,
    LedgerEntry,
    MarginInfo,
    MarginLimitInfo,
    MarginStatus,
    OrderBook,
    OrderBookEntry,
    OrderHistoryItem,
    OrderRequest,
    OrderResponse,
    OrderSide,
    OrderStatus,
    OrderType,
    PaginatedResponse,
    Position,
    PositionHistory,
    PositionStatus,
    Ticker,
    TimeFrame,
    TradeItem,
    WalletBalance,
    WalletSummary,
    WalletType,
    WebSocketAuthRequest,
    WebSocketSubscriptionRequest,
)

__all__ = tuple(sorted([
    # Enums
    "ApiResponse",
    "Candle",
    "ClosePositionResponse",
    "LedgerEntry",
    "MarginInfo",
    "MarginLimitInfo",
    "MarginStatus",
    "OrderBook",
    "OrderBookEntry",
    "OrderHistoryItem",
    "OrderRequest",
    "OrderResponse",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "PaginatedResponse",
    "Position",
    "PositionHistory",
    "PositionStatus",
    "Ticker",
    "TimeFrame",
    "TradeItem",
    "WalletBalance",
    "WalletSummary",
    "WalletType",
    "WebSocketAuthRequest",
    "WebSocketSubscriptionRequest",
]))
