name: Backend CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tradingbot-backend
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PYTHONUNBUFFERED: "1"
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Validate installed packages
        run: pip check

      - name: Lint (critical rules only)
        run: python -m ruff check --select E9,F63,F7,F82

      - name: Run tests
        run: python -m pytest --tb=short -q
