name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tradingbot-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: 'tradingbot-backend/requirements.txt'

      - name: Upgrade pip and install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mypy bandit pip-audit

      - name: Type-check (mypy)
        run: |
          mypy --ignore-missing-imports --install-types --non-interactive . || true

      - name: Security (bandit)
        run: |
          bandit -q -r . -c bandit.yaml || true

      - name: Security (pip-audit)
        run: |
          pip-audit -r requirements.txt || true

      - name: Run tests
        env:
          AUTH_REQUIRED: "False"
          WS_CONNECT_ON_START: "0"
          BITFINEX_API_KEY: ""
          BITFINEX_API_SECRET: ""
        run: pytest -q

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/dashboard
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: frontend/dashboard/package-lock.json

      - name: Install
        run: npm ci

      - name: Debug - Check file structure
        run: |
          pwd
          ls -la src/lib/
          ls -la tsconfig.json
          cat tsconfig.json

      - name: Typecheck
        run: npm run typecheck --silent

      - name: Build
        run: npm run build --silent
