name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend:
    name: Backend CI
    runs-on: windows-latest
    defaults:
      run:
        working-directory: tradingbot-backend
    env:
      PYTHONIOENCODING: utf-8
      PYTHONLEGACYWINDOWSSTDIO: utf-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Validate installed packages
        run: pip check

      - name: Lint (critical rules only)
        run: python -m ruff check --select E9,F63,F7,F82

      - name: Run tests
        run: python -m pytest --tb=short -q

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/dashboard
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: frontend/dashboard/package-lock.json

      - name: Install
        run: npm ci

      - name: Debug - Check file structure
        run: |
          pwd
          ls -la src/lib/
          ls -la tsconfig.json
          cat tsconfig.json

      - name: Typecheck
        run: npm run typecheck --silent

      - name: Build
        run: npm run build --silent
