name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend:
    name: Backend CI
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r tradingbot-backend/requirements.txt
          python -m pip install pylint==3.2.6

      - name: Run CI script
        shell: pwsh
        run: |
          ./tradingbot-backend/scripts/ci.ps1

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/dashboard
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/dashboard/package-lock.json

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npx tsc -b --pretty false

      - name: Build
        run: npm run build --silent
